(define (sqrt x)
  (define (average x y)
    (/ (+ x y) 2)
  )
  (define (improve guess x)
    (average guess (/ x guess))
  )
  ;变化率很小时结束
  (define (good-enough? preGuess guess)
    (<= (abs (/ (- guess preGuess) guess))
        0.001
    )
  )
  (define (sqrt-iter preGuess guess x)
    (cond ((= x 0) 0)
          ((good-enough? preGuess guess) guess)
          (else (sqrt-iter guess (improve guess x) x))
    )      
  )
  (sqrt-iter 0.0 1.0 x)
)
