(define (cubr x)
  (define (sum-and-divide-3 a b)
    (/ (+ a b) 3)
  )
  (define (square a)
    (* a a)
  )
  (define (improve guess)
    (sum-and-divide-3 (/ x (square guess))
              (* 2 guess)
    )
  )
  (define (good-enough? guess)
    (<= (abs (- (improve guess)
                guess)
        )
        0.001
    )
  )
  (define (cubr-iter guess)
    (cond ((= x 0) 0)
          ((good-enough? guess) guess)
          (else (cubr-iter (improve guess)))
    )
  )
  (cubr-iter 1.0)
)

(display (cubr 125))
(newline)
(display (cubr 0))
(exit)
